### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by mrtkp9993** [iampavangandhi/Gitwar#13]
![Screen Shot 2020-12-30 at 08 45 25](https://user-images.githubusercontent.com/17238910/103332541-6623ff00-4a7b-11eb-9e3d-4421163bc8c2.png)

**Comment by iampavangandhi** [comment]
@mrtkp9993 I am using a free heroku dyno for Gitwar as so many of you are using Gitwar it's monthly bandwidth is exhausted. You can deploy it on your heroku account to use it without any worry or wait for 2-3 days.
