### ISSUE TITLE
Check Score Not Working

### ISSUE THREAD

**Issue by ksdkamesh99** [iampavangandhi/Gitwar#15]
Hi @iampavangandhi 

There is an issue with the check score. If we want to check the score of the GitHub username then this error page is referring to. Kindly check it. 

I attached the screenshot for reference.

![image](https://user-images.githubusercontent.com/46109386/104742823-f0a17980-5770-11eb-9557-454b557c67b4.png)

**Comment by iampavangandhi** [comment]
Hi @ksdkamesh99, I am using free versions of everything for Gitwar and Due to multiple requests at a time sometimes it gives error.

Here is your score card
![image](https://user-images.githubusercontent.com/42767012/104799364-a1049180-57f4-11eb-8f79-27ec935be7d2.png)
