### ISSUE TITLE
Error Fetching Resource - 502

### ISSUE THREAD

**Issue by rammazzoti2000** [iampavangandhi/Gitwar#22]
The badge seems to have stopped working.
On my profile it appears as broken, while if I click on it, it shows `Error Fetching Resource` with a `502 bad gateway` error in  browser's console.

Also the deployed link appears to be broken too => https://gitwar.herokuapp.com/
![image](https://user-images.githubusercontent.com/3244654/126703080-5cab89f5-2653-46f5-a9ca-118c5f89aeae.png)

I really like this badge and would really appreciate if you can fix it.

Thank you very much,
Alex

**Comment by iampavangandhi** [comment]
Hi @rammazzoti2000, Actually I am using a free dyno of Heroku which have some monthly limit as I am a student and don't have budget to run the project on paid server. I think the monthly limit exhausted. You can host the project on your own servers or wait till 1st August for the limit to renew. 🤓

**Comment by rammazzoti2000** [comment]
> Hi @rammazzoti2000, Actually I am using a free dyno of Heroku which have some monthly limit as I am a student and don't have budget to run the project on paid server. I think the monthly limit exhausted. You can host the project on your own servers or wait till 1st August for the limit to renew. 🤓

@iampavangandhi thank you for answering.
I guess that's what I am going to do ☺️.
Thanks for the tip.

Great job with the badge, cheers.
