### ISSUE TITLE
Compete and Check your Score Functionalities not working

### ISSUE THREAD

**Issue by Subhampreet** [iampavangandhi/Gitwar#23]
The "Compete" and "Check your Score" functionalities aren't producing the desired outputs and throwing an error 404. I can resolve the issue if you would assign me this issue to work on as well as some enhancement of UI can be made (For ex: Light/Dark Mode)

**Comment by iampavangandhi** [comment]
Hi, @Subhampreet the 404 error is because of GitHub API rate limit for non loggedin user. Yes you can work on the project UI and Features 😊

**Comment by Subhampreet** [comment]
@iampavangandhi I will be glad to contribute to this project and develop the UI 😇
