### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by iampavangandhi** [iampavangandhi/Gitwar#5]
Improve the Frontend and Make it Attractive and Responsive :rainbow:

**Comment by Zeeshan-2k1** [comment]
@iampavangandhi I want to take this. Can u please tell what type of design I should make?

**Comment by iampavangandhi** [comment]
@Zeeshan-2k1 You don't have to make it from scratch. just have to improve.

**Comment by karans5004** [comment]
@iampavangandhi  : Is this still open for enhancements?

**Comment by iampavangandhi** [comment]
@karans5004 Yes it's still open but make sure to retain the responsiveness while changing anything
