### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by mirsazzathossain** [iampavangandhi/Gitwar#8]

**Comment by iampavangandhi** [comment]
@mirsazzathossain What resources you want?

**Comment by mirsazzathossain** [comment]
In gitwar score badge, it is showing "resource not found"

**Comment by mirsazzathossain** [comment]
https://gitwar.herokuapp.com/badge?username=mirsazzathossain

**Comment by iampavangandhi** [comment]
@mirsazzathossain There is a limit for the Github API and Heroku that's why It shows resources not found sometimes. I suggest you fork it and deploy yourself on your heroku dyno to avoid this issue

**Comment by mirsazzathossain** [comment]
Okey got it.
